### ISSUE TITLE
2 app folders being created under Windows' `%appdata%`

### ISSUE THREAD

**Issue by webmandesign** [absalomedia/vagrant-manager#16]
## Describe the bug

According to a [reply in previous issue](https://github.com/absalomedia/vagrant-manager/issues/10#issuecomment-482803820), the app creates `%appdata%/VagrantManager` folder on Windows computer.

However, I've noticed it also creates the `%appdata%/Vagrant Manager` folder too (still).

Is it really needed for the app to create 2 folders under Windows' `%appdata%`?

## To Reproduce

1. Navigate to Windows' `%appdata%` folder and delete any `Vagrant Manager` and `VagrantManager` subfolders.
2. Start the app. You can see a new `%appdata%/Vagrant Manager` folder was created by the app.
3. Right-click the app icon in taskbar and do vagrant up a machine (box).
4. After the vagrant up task has finished, a new `%appdata%/VagrantManager` folder was created by the app.

We end up with this folder structure then:
```
[dir] %appdata%/Vagrant Manager
⊢ [dir] GPUCache
  ⊢ [file] data_0
  ⊢ [file] data_1
  ⊢ [file] data_2
  ⊢ [file] data_3
  ⊢ [file] index
⊢ [dir] logs
⊢ [file] lockfile
⊢ [file] Preferences

[dir] %appdata%/VagrantManager
⊢ [file] log.log
```

## Expected behavior

Shouldn't the app create only 1 folder under Windows' `%appdata%`?

## Desktop

 - OS: Windows 10
 - Version 2.2.0

**Comment by absalomedia** [comment]
This is an unforeseen byproduct of the build process vs the actual app itself.  It's the Electron builder productName field that sets what the final app/package is going to be called across different platforms. With the product name still set to "Vagrant Manager", across all platforms, Electron still creates a directory for the installed app called "Vagrant Manager".

The main problem from my perspective is that renaming the app to "VagrantManager" as one word isn't the best design or development strategy. It may be better just to standardise the log structure back to normal instead of customised

**Comment by webmandesign** [comment]
I see. Sure, I don't want you to change the name of the app :)

In this case, could the app just use the `%appdata%/Vagrant Manger` folder instead? There is really no need to use the other folder just for log file. Would be sufficient if the log file is created in the `%appdata%/Vagrant Manger` folder instead.

Thanks!
